name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and export Next.js site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/gh-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: out
          token: ${{ secrets.GITHUB_TOKEN }}
